[package]
name = "api-shuttle"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = { workspace = true }
shuttle-actix-web = "0.21.0"
shuttle-runtime = "0.21.0"
tokio = "1.29.1"
api-lib = { workspace = true }
